matrix:
  include:
    - name: 'ShellCheck'
      language: minimal
      script:
        # Run shellcheck on all files that don't contain a .
        - find ${TRAVIS_BUILD_DIR} -path "${TRAVIS_BUILD_DIR}/.git" -prune -or \( -not -name '*.*' -and -type f \) -exec shellcheck '{}' \; -exec false '{}' +


    - name: 'Script Formatting Check'
      language: go
      install:
        - go get -u mvdan.cc/sh/cmd/shfmt
      script:
        - shfmt -i 2 -d .


    # Check all the files in the repository for consistent formatting
    - name: 'File Formatting Checks'
      language: minimal
      script:
        # Check for files starting with a blank line
        - find ${TRAVIS_BUILD_DIR} -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -print0 | xargs -0 -L1 bash -c 'head -1 "$0" | grep --binary-files=without-match --regexp="^$"; if [[ "$?" == "0" ]]; then echo "Blank line found at start of $0."; false; fi'
        # Check for true tabs (except for in keywords.txt, which requires it)
        - find ${TRAVIS_BUILD_DIR} -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -exec grep --with-filename --line-number --binary-files=without-match --regexp=$'\t' '{}' \; -exec echo 'Tab found.' \; -exec false '{}' +
        # Check for non-Unix line endings
        - find ${TRAVIS_BUILD_DIR} -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -exec grep --files-with-matches --binary-files=without-match --regexp=$'\r$' '{}' \; -exec echo 'Non-Unix EOL detected.' \; -exec false '{}' +
        # Check for trailing whitespace
        - find ${TRAVIS_BUILD_DIR} -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -exec grep --with-filename --line-number --binary-files=without-match --regexp='[[:blank:]]$' '{}' \; -exec echo 'Trailing whitespace found.' \; -exec false '{}' +
        # Check for extra blank lines at end of files
        - find ${TRAVIS_BUILD_DIR} -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -print0 | xargs -0 -L1 bash -c 'tail -1 "$0" | grep --binary-files=without-match --regexp="^$"; if [[ "$?" == "0" ]]; then echo "Blank line found at end of $0."; false; fi'


    # Check all files in the repository for commonly misspelled words
    - name: 'Spell Check'
      language: python
      python: 3.6
      install:
        # Install codespell
        # https://github.com/codespell-project/codespell
        - pip install codespell

      script:
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" --ignore-words="${TRAVIS_BUILD_DIR}/etc/codespell-ignore-words-list.txt" "${TRAVIS_BUILD_DIR}"


notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      # TravisBuddy will comment on any pull request that results in a failing CI build
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
