matrix:
  include:
    # Check all files in the repository for commonly misspelled words
    - name: 'Spell Check'
      language: python
      python: 3.6
      install:
        # Install codespell
        # https://github.com/codespell-project/codespell
        - pip install codespell

      script:
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" --ignore-words="${TRAVIS_BUILD_DIR}/etc/codespell-ignore-words-list.txt" "${TRAVIS_BUILD_DIR}"


notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      # TravisBuddy will comment on any pull request that results in a failing CI build
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
