#!/bin/bash

# check for commonly misspelled words
# codespell must be installed: https://github.com/codespell-project/codespell#installation

# configure the path to the codespell ignore words list file
# this list is used to fix false positives
# leave blank if there is no list file
readonly ignoreWordsListPath=""

if [[ ! -e "$(command -v codespell)" ]]; then
  echo 'ERROR: codespell is not installed or not in PATH.'
  echo 'Please install it using: pip install codespell'
  exit 1
fi

# stash so that unstaged changes are not checked
git stash -q --keep-index

# set default exit status
exitStatus=0

while read -r filename; do
  # check if it's a file (find matches on pruned folders)
  if [[ -f "$filename" ]]; then
    # check if the file is tracked by git
    if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
      # don't check untracked files
      continue
    fi

    if [[ "$ignoreWordsListPath" == "" ]]; then
      # there is no ignore words file so don't use the --ignore-words option
      if ! codespell "$filename"; then
        echo "ERROR: Misspelled word found in $filename"
        # make the hook fail
        exitStatus=1
      fi
    else
      if ! codespell --ignore-words="$ignoreWordsListPath" "$filename"; then
        echo "ERROR: Misspelled word found in $filename"
        # make the hook fail
        exitStatus=1
      fi
    fi
  fi
done <<<"$(find . -path './.git' -prune -or -type f)"

git stash pop -q

exit $exitStatus
